language: node_js
node_js: '12'
sudo: enabled
dist: trusty
install:
  - npm ci
cache:
  directories:
    - node_modules
os:
  - linux
  - osx
  - windows
script:
  - npm run build
  - npm run coverage
  - npm run report-coverage
